name: Docs - auto deploy on PR open

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - "feature*"
    paths:
      - "apps/docs-astro/**"

env:
  COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
  BUILD_FOLDER: "${{ github.head_ref }}"
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy:
    name: Deploy Punkt-docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      max-parallel: 1
      matrix:
        node-version: [18.19]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Generate docs for /${{ env.BUILD_FOLDER }}
        run: |
          npx lerna run build --scope=@oslokommune/punkt-docs -- --base='/${{ env.BUILD_FOLDER }}'
          npx lerna run postbuild-fix-astro-paths --scope=@oslokommune/punkt-docs -- base='${{ env.BUILD_FOLDER }}'

      - name: Deploy files for the website to /${{ env.BUILD_FOLDER }}
        run: |
          aws s3 sync ./apps/docs-astro/dist s3://${{ secrets.AWS_S3_PUNKT_WEBSITE }}/${{ env.BUILD_FOLDER }} --delete --cache-control 'max-age=86400'
          AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_PUNKT_DOCS_APP }} --paths "/${{ env.BUILD_FOLDER }}*"

      - name: "Comment on PR"
        if: ${{ github.event.action == 'opened' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SCHJETNE }}
        run: |
          gh pr comment ${{ env.PR_NUMBER }} --body 'Nettstedet finnes på [https://punkt.oslo.kommune.no/${{ env.BUILD_FOLDER }}](https://punkt.oslo.kommune.no/${{ env.BUILD_FOLDER }})'
