name: Vue2 - auto deploy on PR open

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - "feature*"
    paths:
      - "packages/vue2/**"

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  deploy:
    name: Deploy Punkt-vue2 app
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version: [18.19]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Vue2 app
        run: |
          npm run build-assets
          npm run build-css
          npm run build-vue2-app

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy files to vue2.punkt.oslo.systems and clear cache
        run: |
          aws s3 sync ./packages/vue2/dist-app s3://${{ secrets.AWS_S3_PUNKT_VUE2_APP }} --delete --cache-control 'max-age=31536000'
          AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_PUNKT_VUE2_APP }} --paths "/*"

      - name: "Comment on PR"
        if: ${{ github.event.action == 'opened' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SCHJETNE }}
        run: |
          gh pr comment ${{ env.PR_NUMBER }} --body 'Appen kan sees på [https://vue2.punkt.oslo.systems/](https://vue2.punkt.oslo.systems).'
